---
apiVersion: v1
kind: Service
metadata:
  name: hotrod-mapper
  namespace: hotrod
  labels:
    appName: hotrod-mapper
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the route service.
  ports:
  - name: http-hotrod-mapper
    port: 8084
  type: ClusterIP
  selector:
    appName: hotrod-mapper
---
apiVersion: apps/v1beta2 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  namespace: hotrod
  name: hotrod-mapper
spec:
  selector:
    matchLabels:
      appName: hotrod-mapper
  replicas: 3
  template:
    metadata:
      namespace: hotrod
      labels:
        appName: hotrod-mapper
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
    spec:
      containers:
      - name: hotrod-route
        image: index.docker.io/willwangkelda/hotrod-mapper
        imagePullPolicy: Always
        command: ["python3", "app.py"]
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8084
